### ISSUE TITLE
Workflow processes

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/process#12]
Here is a different kind of example than the manufacturing / assembly type of process.  The first example we ran into was translation.  A translation goes through several processes before it is done, but it is still the same resource.  We added the concept of stages, which lives on the resource.  Here is the [use case](https://github.com/valueflows/valueflows/blob/master/use-cases/guerrilla-translation.md).

First cut, focusing on the differences with assembly processes:

Process:
    - Process type: Initial translation
    -- Inflows:
    -- Outflows:
    ---- Produce flow:
    ------ Date: 2016/3/5
    ------ Quantity: 2500
    ------ Unit: Words
    ------ Agent: Stacco
    ------ Resource type: Spanish document
    ------ Resource: Spanish translation of VF intro @ Initial translation

Process:
    - Process type: Edit translation
    -- Inflows:
    ---- To be changed flow:
    ------ Date: 2016/3/5
    ------ Quantity: 2500
    ------ Unit: Words
    ------ Resource type: Spanish document
    ------ Resource: Spanish translation of VF intro @ Initial translation
    -- Outflows:
    ---- Changed flow:
    ------ Date: 2016/3/8
    ------ Quantity: 2500
    ------ Unit: Words
    ------ Agent: Ann Marie
    ------ Resource type: Spanish document
    ------ Resource: Spanish translation of VF intro @ Edit translation

Process:
    - Process type: Proofread translation
    -- Inflows:
    ---- To be changed flow:
    ------ Date: 2016/3/9
    ------ Quantity: 2500
    ------ Unit: Words
    ------ Resource type: Spanish document
    ------ Resource: Spanish translation of VF intro  @ Edit translation
    -- Outflows:
    ---- Changed flow:
    ------ Date: 2016/3/9
    ------ Quantity: 2500
    ------ Unit: Words
    ------ Agent: Guy
    ------ Resource type: Spanish document
    ------ Resource: Spanish translation of VF intro  @ Proofread translation

**Comment by elf-pavlik** [comment]
> Process:
- Process type: Initial translation
-- Inflows:
-- Outflows:
---- Produce flow:

Don't we need the original document on input here?

Can we also switch to YAML ?

Also worth to see how PROV-O models it first... https://github.com/valueflows/valueflows/wiki/Useful-vocabularies

**Comment by fosterlynn** [comment]
>Don't we need the original document on input here?

Probably, if you want to properly give credit, just simplifying the example.

>Can we also switch to YAML ?

Sure. :)

**Comment by fosterlynn** [comment]
>Also worth to see how PROV-O models it first... https://github.com/valueflows/valueflows/wiki/Useful-se

link didn't work

**Comment by elf-pavlik** [comment]
fixed https://github.com/valueflows/valueflows/wiki/Useful-vocabularies

**Comment by fosterlynn** [comment]
OK here's my YAML attempt.  Apologies for syntax errors.  Also, I'm not sure how to represent an n-ary thing, which I'm modeling the rea:EconomicEvents as.

```yml
'@context':
  qudt: http://qudt.org/1.1/schema/qudt#
  unit: http://qudt.org/1.1/schema/unit#
  vf: https://w3id.org/valueflows/
  ex: https://example.org/

'@graph':

  - '@id': urn:ex:Translate-VF-Intro-initial-translation-2016-03-01
    '@type': vf:Process
    'vf:processType': urn:ex:initial-translation
    'vf:produce': 
        'vf:name': Produce Spanish Translation of VF Intro
        'vf:date": 2016/3/5
        'vf:amount':
            '@type': qudt:QuantityValue
            'qudt:unit': unit:Words
            'qudt:numericValue': 2500
        'vf:involvedAgent': urn:ex:Stacco
        'vf:resource': urn:ex:Spanish-translation-of-VF-intro

  - '@id': urn:ex:Spanish-translation-of-VF-intro
    '@type': vf:Resource
    'vf:resourceType': urn:ex:Spanish-document
    'vf:stage': urn:ex:initial-translation
    'vf:amount':
      '@type': qudt:QuantityValue
      'qudt:unit': unit:Words
      'qudt:numericValue': 2500

  - '@id': urn:ex:Edit-VF-Intro-initial-translation-2016-03-07
    '@type': vf:Process
    'vf:processType': urn:ex:edit-translation
    'vf:accept': 
        'vf:name': Accept Spanish Translation of VF Intro
        'vf:date": 2016/3/7
        'vf:amount':
            '@type': qudt:QuantityValue
            'qudt:unit': unit:Words
            'qudt:numericValue': 2500
        'vf:resource': urn:ex:Spanish-translation-of-VF-intro
    'vf:improve': 
        'vf:name': Improve Spanish Translation of VF Intro
        'vf:date": 2016/3/8
        'vf:amount':
            '@type': qudt:QuantityValue
            'qudt:unit': unit:Words
            'qudt:numericValue': 2500
        'vf:involvedAgent': urn:ex:Guy
        'vf:resource': urn:ex:Spanish-translation-of-VF-intro

  - '@id': urn:ex:Spanish-translation-of-VF-intro
    '@type': vf:Resource
    'vf:resourceType': urn:ex:Spanish-document
    'vf:stage': urn:ex:edit-translation
    'vf-x:amount':
      'qudt:unit': unit:Words
      'qudt:numericValue': 2500

  - '@id': urn:ex:Proofread-VF-Intro-initial-translation-2016-03-10
    '@type': vf:Process
    'vf:processType': urn:ex:proofread-translation
    'vf:accept': 
        'vf:name': Accept Spanish Translation of VF Intro
        'vf:date": 2016/3/10
        'vf:amount':
            '@type': qudt:QuantityValue
            'qudt:unit': unit:Words
            'qudt:numericValue': 2500
        'vf:resource': urn:ex:Spanish-translation-of-VF-intro
    'vf:improve': 
        'vf:name': Improve Spanish Translation of VF Intro
        'vf:date": 2016/3/11
        'vf:amount':
            '@type': qudt:QuantityValue
            'qudt:unit': unit:Words
            'qudt:numericValue': 2500
        'vf:involvedAgent': urn:ex:Alice
        'vf:resource': urn:ex:Spanish-translation-of-VF-intro
        
  - '@id': urn:ex:Spanish-translation-of-VF-intro
    '@type': vf:Resource
    'vf:resourceType': urn:ex:Spanish-document
    'vf:stage': urn:ex:proofread-translation
    'vf-x:amount':
      'qudt:unit': unit:Words
      'qudt:numericValue': 2500      
```

**Comment by elf-pavlik** [comment]
Awesome @fosterlynn !!!
My current process *vf:accept* your snippet and yields it via *vf:improve* (at least I hope :wink: )

```yml
'@context':
  qudt: http://qudt.org/1.1/schema/qudt#
  unit: http://qudt.org/1.1/schema/unit#
  vf: https://w3id.org/valueflows/
  ex: https://example.org/

'@graph':

  - '@id': ex:Translate-VF-Intro-initial-translation-2016-03-01
    '@type': vf:Process
    'vf:processType': ex:initial-translation
    'vf:flow':
      - '@id': ex:input-1
        'vf:name': Cite original VF Intro
        'vf:date': 2016/3/5
        'vf:verb': vf:cite
        'vf:involvedAgent': ex:Stacco
        'vf:resource': ex:original-VF-intro
        'vf:amount':
            '@type': qudt:QuantityValue
            'qudt:unit': unit:Words
            'qudt:numericValue': 2500
      - '@id': ex:output-1
        'vf:name': Produce Spanish Translation of VF Intro
        'vf:date': 2016/3/5
        'vf:verb': vf:produce
        'vf:involvedAgent': ex:Stacco
        'vf:resource': ex:Spanish-translation-of-VF-intro
        'vf:amount':
            '@type': qudt:QuantityValue
            'qudt:unit': unit:Words
            'qudt:numericValue': 2500

  - '@id': ex:Spanish-translation-of-VF-intro-v1
    '@type': vf:Resource
    'vf:resourceType': ex:Spanish-document
    'vf:amount':
      '@type': qudt:QuantityValue
      'qudt:unit': unit:Words
      'qudt:numericValue': 2500
    '@reverse':
      'vf:resource': ex:output-1
      'vf:version': ex:Spanish-translation-of-VF-intro

  - '@id': ex:Edit-VF-Intro-initial-translation-2016-03-07
    '@type': vf:Process
    'vf:processType': ex:edit-translation
    'vf:flow':
      - '@id': ex:input-2
        'vf:name': Accept Spanish Translation of VF Intro
        'vf:date': 2016/3/7
        'vf:verb': vf:accept
        'vf:involvedAgent': ex:Guy
        'vf:resource': ex:Spanish-translation-of-VF-intro-v1
        'vf:amount':
          '@type': qudt:QuantityValue
          'qudt:unit': unit:Words
          'qudt:numericValue': 2500
      - '@id': ex:output-2
        'vf:name': Improve Spanish Translation of VF Intro
        'vf:date': 2016/3/8
        'vf:verb': vf:improve
        'vf:involvedAgent': ex:Guy
        'vf:involvedAgent': ex:Guy
        'vf:resource': ex:Spanish-translation-of-VF-intro-v2
        'vf:amount':
            '@type': qudt:QuantityValue
            'qudt:unit': unit:Words
            'qudt:numericValue': 2500

  - '@id': ex:Spanish-translation-of-VF-intro-v2
    '@type': vf:Resource
    'vf:resourceType': ex:Spanish-document
    'vf:amount':
      'qudt:unit': unit:Words
      'qudt:numericValue': 2500
    'vf:previous': ex:Spanish-translation-of-VF-intro-v1
    '@reverse':
      'vf:resource': ex:output-2
      'vf:version': ex:Spanish-translation-of-VF-intro

  - '@id': ex:Proofread-VF-Intro-initial-translation-2016-03-10
    '@type': vf:Process
    'vf:processType': ex:proofread-translation
    'vf:flow':
      - '@id': ex:input-3
        'vf:name': Accept Spanish Translation of VF Intro
        'vf:date': 2016/3/10
        'vf:verb': vf:accept
        'vf:involvedAgent': ex:Alice
        'vf:resource': ex:Spanish-translation-of-VF-intro-v2
        'vf:amount':
            '@type': qudt:QuantityValue
            'qudt:unit': unit:Words
            'qudt:numericValue': 2500
      - '@id': ex:output-3
        'vf:name': Improve Spanish Translation of VF Intro
        'vf:date': 2016/3/11
        'vf:verb': vf:improve
        'vf:involvedAgent': ex:Alice
        'vf:resource': ex:Spanish-translation-of-VF-intro-v3
        'vf:amount':
            '@type': qudt:QuantityValue
            'qudt:unit': unit:Words
            'qudt:numericValue': 2500

  - '@id': ex:Spanish-translation-of-VF-intro-v3
    '@type': vf:Resource
    'vf:resourceType': ex:Spanish-document
    'vf:amount':
      'qudt:unit': unit:Words
      'qudt:numericValue': 2500
    'vf:previous': ex:Spanish-translation-of-VF-intro-v2
    '@reverse':
      'vf:resource': ex:output-3
      'vf:version': ex:Spanish-translation-of-VF-intro

  - '@id': ex:Spanish-translation-of-VF-intro
    '@type': vf:Resource
    'vf:resourceType': ex:Spanish-document
    'vf:version':
      - ex:Spanish-translation-of-VF-intro-v1
      - ex:Spanish-translation-of-VF-intro-v2
      - ex:Spanish-translation-of-VF-intro-v3

```

1) for linking to N-ary relation from process I used generic *vf:flow*, the value of *vf:verb* marks the direction
2) resources need to stay versioned
  * each version links to a previous version with common *ianarel:previous*
  * HEAD version `ex:Spanish-translation-of-VF-intro` links to all versions with *vf:version*
  * i emphasise it by adding same link in reverse direction using JSON-LD `@reverse`
3) If we want to use process type to mark stage, we can link resource at certain version to the output it came out of. Each output already creates that edge with *vf:resource* so I emphasise its presence by adding it in serialization second time using JSON-LD `@reverse`. We can than **follow our nose** again in reverse direction via *vf:flow* edge and there we can find type of the process that output that resource at that version.

**Comment by elf-pavlik** [comment]
Regarding versioning
* ex:Spanish-translation-of-VF-intro denotes the [g-box](https://www.w3.org/2011/rdf-wg/wiki/Graph_Terminology#g-box)
* ex:Spanish-translation-of-VF-intro-v1 denotes on of its [g-snap](https://www.w3.org/2011/rdf-wg/wiki/Graph_Terminology#g-snap)
* if we make HTTP request and content negotiate for JSON-LD or Turtle, we would get [g-text](https://www.w3.org/2011/rdf-wg/wiki/Graph_Terminology#g-text)

![graph-terms](https://www.w3.org/2011/rdf-wg/wiki/images/b/bc/Graph-concepts.png)

**Comment by fosterlynn** [comment]
>My current process vf:accept your snippet and yields it via vf:improve (at least I hope :wink: )

Excellent! :wink:

>for linking to N-ary relation from process I used generic vf:flow, the value of vf:verb marks the in/out direction

How does the computer know the direction from the verb?

>resources need to stay versioned

This is interesting.  Said in chat, but I think we will need to support versioning (which mine didn't) and not-versioning, i.e. the same resource follows through the series of processes.  You can version electronic resources, but not material resources.  Need lots more thought into versioning question.  Not sure if versioning is part of this pattern, or something along side of it.

> also added vf:cite of original document, processes which give output but don't take input smell to much like some magic tricks or the myth about Big Bang

That is good of you, let's keep it in our examples! :smile:

**Comment by elf-pavlik** [comment]
> How does the computer know the direction from the verb?

In [process.ttl](https://github.com/valueflows/process/blob/master/process.ttl) we have 

```ttl
vf:cite
  a rdf:Property ;
  rdfs:subPropertyOf vf:infow .

vf:accept
  a rdf:Property ;
  rdfs:subPropertyOf vf:infow .

vf:create
  a rdf:Property ;
  rdfs:subPropertyOf vf:outflow .

vf:improve
  a rdf:Property ;
  rdfs:subPropertyOf vf:outflow .
```

So we get *vf:inflow* or *vf:outflow* from that

> This is interesting. Said in chat, but I think we will need to support versioning (which mine didn't) and not-versioning, i.e. the same resource follows through the series of processes. You can version electronic resources, but not material resources. Need lots more thought into versioning question. Not sure if versioning is part of this pattern, or something along side of it.

I think we can do that. We could use that *vf:stage* edge and just change where it points. Yo would not know the state of resource after each process but if you don't want versions that suggests that you don't care about knowing those states. When we do that, let's don't use single YAML snippet with single `@graph`, but for each 'snapshot' of the data about resource we write separate YAML snippet with its own `@graph`.

```yaml
'@context':
  - https://w3id.org/valueflows/v1
  - ex:
      https://example.org/
'@graph':
  - '@id': ex:Spanish-translation-of-VF-intro
    '@type': vf:Resource
    'vf:resourceType': ex:Spanish-document
    'vf:stage': ex:initial-translation
    'vf:amount':
      '@type': qudt:QuantityValue
      'qudt:unit': unit:Words
      'qudt:numericValue': 2500
```
later
```yaml
'@context':
  - https://w3id.org/valueflows/v1
  - ex:
      https://example.org/
'@graph':
  - '@id': ex:Spanish-translation-of-VF-intro
    '@type': vf:Resource
    'vf:resourceType': ex:Spanish-document
    'vf:stage': ex:edit-translation
    'vf:amount':
      '@type': qudt:QuantityValue
      'qudt:unit': unit:Words
      'qudt:numericValue': 2500
```
later
```yaml
'@context':
  - https://w3id.org/valueflows/v1
  - ex:
      https://example.org/
'@graph':
  - '@id': ex:Spanish-translation-of-VF-intro
    '@type': vf:Resource
    'vf:resourceType': ex:Spanish-document
    'vf:stage': ex:proofread-translation
    'vf:amount':
      '@type': qudt:QuantityValue
      'qudt:unit': unit:Words
      'qudt:numericValue': 2500
```

**Comment by bhaugen** [comment]
> You would not know the state of resource after each process

You could know what went into the process (e.g. new parts on bicycle), and what the process type was, and if there were other outputs (old bike parts, for example). Processes usually have descriptions, as well, and output events also have descriptions. So you could know quite a lot.

**Comment by elf-pavlik** [comment]
@bhaugen how does it apply to the `ex:edit-translation` process? all we record that same document goes in and goes out, and both events just record same number of words (2500). We could attach the diff somewhere, which compares version on input with version on output. That looks like a version control but done by keeping track of deltas, as git does.

**Comment by elf-pavlik** [comment]
> all we record that same document goes in and goes out, and both events just record same number of words (2500).

again it looks that we measure the resource (document) not the event! can we try this example with document that has chapters and we translate it chapter by chapter?

**Comment by bhaugen** [comment]
> both events just record same number of words (2500).

We never actually did this. The Guerrilla Translators wanted to use NRP for a commercial translation org, which never happened. The number of words was a rough guess, and it would not mean the number of words in the document unless it was the initial creation of the translated document. After that, it would be a measure of the effort (e.g. editing) that went into the next process. Words could still be used, but they would be used to reward the editor. Like, editing a document of 2500 words is worth N euros.

> again it looks that we measure the resource (document) not the event! 

They were measuring the event: the effort that went into the process of taking the document to its next stage.

> can we try this example with document that has chapters and we translate it chapter by chapter?

Sure. In that case, each chapter would be a separate resource, which would be related to the whole document.

**Comment by fosterlynn** [comment]
@elf-pavlik a question: Why do you include vf:cite and vf:create in both the process and the flows that are within the process? 

```yml
  - '@id': ex:Translate-VF-Intro-initial-translation-2016-03-01
    '@type': vf:Process
    'vf:cite': ex:original-VF-intro
    'vf:create': ex:Spanish-translation-of-VF-intro-v1
    'vf:flow':
      - '@id': ex:input-1
        'vf:name': Cite original VF Intro
        'vf:date': 2016/3/5
        'vf:verb': vf:cite
        'vf:involvedAgent': ex:Stacco
      - '@id': ex:output-1
        'vf:name': Produce Spanish Translation of VF Intro
        'vf:date': 2016/3/5
        'vf:verb': vf:produce
        'vf:involvedAgent': ex:Stacco
```

**Comment by elf-pavlik** [comment]
@fosterlynn I just did it to showcase n-ary relation and it's direct version next to each other. 

This snippet:
```yaml
  - '@id': ex:Translate-VF-Intro-initial-translation-2016-03-01
    '@type': vf:Process
    'vf:flow':
      - 'vf:verb': vf:cite
        'vf:resource': ex:original-VF-intro
```
should allow to infer

```yaml
  - '@id': ex:Translate-VF-Intro-initial-translation-2016-03-01
    '@type': vf:Process
    'vf:cite': ex:original-VF-intro
```

and in practice they express exactly the same knowledge! the n-ary version just allows to add more information while direct relation just has label (predicate which has direction, not to confuse with in/out flow direction!)

In your snippet you don't need the direct relation since you use n-ary, still in other cases someone might choose to use just the direct version and you would not find n-ary version.

**Comment by fosterlynn** [comment]
@elf-pavlik sorry, I just found your comment above.  And the above explanation helps more too.

>To better illustrate n-ary relation I added redundant

**Comment by fosterlynn** [comment]
>When we do that, let's don't use single YAML snippet with single @graph, but for each 'snapshot' of the data about resource we write separate YAML snippet with its own @graph.

@elf-pavlik a couple questions:

1. What is the significance of one vs 3 @graph's in general?

2. In this case, you could draw the same directed graph even though it is one resource and you now have only the current stage of the resource defined explicitly.  You still know that the resource was output from the earlier processes.  Does this matter in your recommendation to split the @graphs?

**Comment by elf-pavlik** [comment]
I think 3 separate snippets make it less likely to interpret what you write as 

```yaml
'@context':
  - https://w3id.org/valueflows/v1
  - ex:
      https://example.org/
'@graph':
  - '@id': ex:Spanish-translation-of-VF-intro
    '@type': vf:Resource
    'vf:resourceType': ex:Spanish-document
    'vf:stage':
      - ex:initial-translation
      - ex:edit-translation
      - ex: proofread-translation
    'vf:amount':
      '@type': qudt:QuantityValue
      'qudt:unit': unit:Words
      'qudt:numericValue': 2500
```

Above would happen if you run JSON-LD expansion and than compact it again, as explained in https://www.youtube.com/watch?v=Tm3fD89dqRE
