### ISSUE TITLE
how to distinguish the desired output(s)

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/process#14]
In case of [Porridge preparation](https://github.com/valueflows/valueflows/blob/master/use-cases/porridge-preparation.md). The 3 servings of porridge I would consider _desired_ output, the one that motivates executing the process. Peals and gray water come also as output but they didn't motivate that process.

IMO we need a way to distinguish those outputs. @bhaugen mention during recent chat 'recipe for product' where in this case we produce '3 servings of porridge', we don't usually make recipes for 'gray water' or 'fruit & vegetable peals'.

**Comment by elf-pavlik** [comment]
It also relates to [Goal (Intent?) -> Recipes -> Plans -> Reality](https://github.com/valueflows/valueflows/issues/110) where we evaluate available alternative recipes which produce output matching the desired/intended one.

**Comment by bhaugen** [comment]
Some terms from manufacturing might help: desired outputs from the same process are Coproducts. Not-so-desired outputs are Byproducts. Byproducts that can be recycled into the same process (like flash from molding) are less undesirable than byproducts that need to be disposed of (which are also called waste), and even more undesirable are toxic byproducts (which are also called toxic wastes), which I can't imagine calling a product of any kind, but look it up, they do...

**Comment by elf-pavlik** [comment]
On *selfdogfood* side, we can mark VF ontology as one of the desired outputs.

**Comment by elf-pavlik** [comment]
from gitter
> @elf-pavlik do we need a service or just process that describes change to the state of resources
> @fosterlynn thinking about this.... seems like if the change of location was for the reason of some other process, and you will want to trace it back directly as a contributory input to that process, you will need a service, otherwise not
