### ISSUE TITLE
modeling human metabolism as vf:Transformation

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/process#16]
I will focus on expanding [Porridge preparation](https://github.com/valueflows/valueflows/blob/master/use-cases/porridge-preparation.md) to include full economic cycle. It seems that currently we have at least on obvious missing link.

1) I executed porridge preparation plan
2) We have 3 outputs
- 3 servings of porridge
- gray water
- fruit peals and seeds
  3) gray water goes into sewerage or some natural local pond (water treatment process)
  4) fruit peals go into composter (composting process)
  5) 3 servings of porridge go ...???

Human (or any other animal) metabolism seems to fit [vf:Transformation](https://github.com/valueflows/process/blob/master/Transformation.md). We have inputs and outputs, mostly
- input: Food, Drinks
- output: Humanure, Urine

I think each instance of vf:Person can have one-to-one relation with an instance of _vf:Transformation_ representing metabolism of that person. This also fits [relating Intent to a Process, and to other resources via its inputs/outputs](https://github.com/valueflows/valueflows/issues/118). People hopefully will make different decision, if someone asks food to eat it onself, or asks food to exchange it for 'money'. Also in some way related [Food Stamps](https://github.com/valueflows/exchange/issues/3)

**Comment by bhaugen** [comment]
http://locecon.org/clusters/network/8/
http://locecon.org/clusters/network/1/
Based on same model as VF. We want to connect with whole ecocycles, but need people to work with on it.

**Comment by elf-pavlik** [comment]
Actually now I think to NOT define *vf:Agent* and *vf:Process* as disjoint classes. So we could write
```yaml
'@context': https://w3id.org/valueflows/
'@type':
  - vf:Agent
  - vf:Process
name: elf Pavlik
```

We can see work I do as a resource output by my general life process. This process also requires inputs. I need a way to draw a dependency between work I do and food I eat etc.

In this case, while I contribute to value flows ontology, it could include food i eat as it's indirect dependency. People who value valueflows, could support it by providing for example rolled oats for me :smile_cat:

**Comment by elf-pavlik** [comment]
We may also need to model *vf:Process* aspect of other animals. For example a goat (the one name "Molly") eats grass and sometimes gives milk. This goat provides lawn moving service (vf:Service, vf:work) and sometimes also creates milk (*vf:create*).

**Comment by bhaugen** [comment]
Goats also eliminate poison ivy and similar noxious weeds. And they are very intelligent and playful, so they are sometimes better companions for children than dogs.

The Amish around us use horses as draft animals for farming and to pull wagons and carriages for transportation.

See also Odum's [Emergy models](https://en.wikipedia.org/wiki/Emergy).

**Comment by elf-pavlik** [comment]
https://en.wikipedia.org/wiki/Livelihood may provide better concept than metabolism
