### ISSUE TITLE
start & stop events for usage & work (similar to load & unload) in transportation

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/process#23]
It looks like currently we can't track in real time which tools and people stay occupied (blocked) by which processes. With only _use_ and _work_ events we can't track the start and stop of work and usage. Many processes will also allow interruption so single usage and work will have multiple _start_ and _stop_ events referencing them.

**Comment by fosterlynn** [comment]
>It looks like currently we can't track in real time which tools and people stay occupied (blocked) by which processes.

Why not?  In NRP we can track work that way if people use the page with the timer.

>Many processes will also allow interruption so single usage and work will have multiple start and stop events referencing them.

I think those should be different events then.  Although maybe we can allow either, I don't know.

**Comment by bhaugen** [comment]
See also https://github.com/valueflows/valueflows/issues/152

**Comment by elf-pavlik** [comment]
> Why not? In NRP we can track work that way if people use the page with the timer.

Could you write YAML snippet of what data you get when using 'timer'?

**Comment by fosterlynn** [comment]
I think it just keeps adding minutes to the event record until they hit Stop.  We don't do anything about blocking people, but I don't know why we couldn't.  Would need more data than the vf:eventQuantity (name tbd).  Maybe that's what you mean about we can't track in real time?  If so, I get it now - yes, we do need more start/stop or start/duration data in the events in VF, a la the issue Bob referenced above.  We do have a vf:eventDate, maybe that should be a date-time.... but let's do some work on that problem.
