### ISSUE TITLE
Composable events (event types)

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/process#24]
Some initial discussion starting here: https://github.com/valueflows/valueflows/issues/157#issuecomment-250931945

**Comment by elf-pavlik** [comment]
Since various actions carried by events have different effect on resources, we could also explore using some kind of patch format which would provide flexible way to express those effects.
* https://www.w3.org/TR/ldpatch/
* http://jsonpatch.com/

**Comment by bhaugen** [comment]
Example of how a patch format might be used to do that?

**Comment by bhaugen** [comment]
I'd like to see a combined or compound action also *be* an action, expressible in a single active verb in a sentence, as in https://github.com/valueflows/valueflows/issues/160

**Comment by fosterlynn** [comment]
On a quick study: Patch seems to be more to make changes to something that you don't need the history for anything except to know what changes were made when.  Our events seem different, because they form chains of nodes and edges that we need to traverse.  Patch seems more like you changed your mind or need to fix something, not so much recording a series of things that happened - you could have a list of patches to a record, but not an IPO chain. 

??
