### ISSUE TITLE
skills related to operating tools used in a process

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/process#25]
use case we shortly discussed with @fosterlynn on gitter https://gitter.im/valueflows?at=5836f6ba381827c24d76f394

* planned process which requires 1 tractor, 5 chainsows, 30 axex and 100 people to help
* 2 people need to have 'use tractro' skill, 10 'use chainsow' and 50 'use axe'

**Comment by bhaugen** [comment]
I'd love to work through an example of this set of issues with some real-life community that wants to use it in a computer system. When we ran into one variation at Sensorica, it was framed as access rules for the 3d printer, in that you needed to be trained specifically for that machine. (Note: we never implemented them other than as a textual description.)

Around us, likewise, we don't believe "chainsaw skills" unless somebody has passed the class.

So this can become complex, involving skills, credentials, and access rules for equipment resources.

**Comment by elf-pavlik** [comment]
I agree that many claims need to get proven in real world situation. I think issue above relates mostly to creating intents based on plan of a process.
We can leave this issue as a placeholder until I get solid-character production ready and start working on task management app which will match skillset of person using it with all the tasks related to the projects this person would like to support (make contributions to). Since I currently focus on software projects, eventually it should also include task related to all the dependencies. So one can support the project also by contributing to any of it dependencies :)
