### ISSUE TITLE
Process Type taxonomy

### ISSUE THREAD

**Issue by bhaugen** [valueflows/process#3]
Process Types come in a taxonomy, with meta-types and recipe-layer types all over the place.

For example, #2 assembly and disassembly.

Lots of Forming process types: molding, stamping, pressing, etc.

Lots of food process types, like mixing, leavening, fermenting, baking, frying, boiling, steaming, etc.

Baking recipes have their own conventions: e.g. [Baker's Percentage](https://en.wikipedia.org/wiki/Baker_percentage).

Lots of chemical process types.

Then in the recipe layer, like IPO tables, we would find application of a meta type to specific input and output resource types.

Like, assemble and disassemble a wooden dome.

Then, a particular instance of assembling a wooden dome at POC21 and then disassembling.

Back to the meta-types: I might have a chance in the near future to work with some manufacturing experts in defining some of them. Will report back.

**Comment by elf-pavlik** [comment]
In vf: namespace, we define so far two OWL/RDFS sub classes of *vf:Process*
* *vf:Transformation*
* *vf:Transportation*

> Lots of Forming process types: molding, stamping, pressing, etc.
> Lots of food process types, like mixing, leavening, fermenting, baking, frying, boiling, steaming, etc.

They all seam to fit *vf:Transformation*. Maybe such specific variants/kinds we can base on http://dbpedia.org/ & https://www.wikidata.org/

**Comment by bhaugen** [comment]
@elf-pavlik - I'm not sure what you intend for subclasses of vf:Process. Do you mean to replace ProcessType as its own vf:Concept? Or that ProcessType would have its own taxonomy?

(ProcessTypes and TransferTypes are important recipe components.)

**Comment by elf-pavlik** [comment]
![NRP Process](https://camo.githubusercontent.com/4e022abb6358edae8b381fedf1899d23b8eaac2e/68747470733a2f2f692e696d6775722e636f6d2f373467495935432e706e67)

does diagram above show only instances? 
Recipe shows **instances** of ProcessType
Plan shows **instances** of Process

**Comment by bhaugen** [comment]
Yes, those are all instances. ProcessType is a type object. Those are all instances of user-defined types.

**Comment by bhaugen** [comment]
What we have done in previous projects for type object taxonomies is to have parent-child relationships between them, where the parent type is skos:broader. (E.g. Herb parent:child Rosemary.) We've done this a lot with ResourceTypes; not yet with ProcessTypes, but it is certainly doable and we might want to do it in VF.

**Comment by ahdinosaur** [comment]
keen to use [skos#semantic-relations](https://www.w3.org/TR/skos-reference/#semantic-relations)

**Comment by elf-pavlik** [comment]
@ahdinosaur you can find example of food related SKOS thesaurus here: http://aims.fao.org/standards/agrovoc

please also read: https://www.w3.org/2006/07/SWD/SKOS/skos-and-owl/master.html

**Comment by bhaugen** [comment]
agrovoc also posted on https://github.com/valueflows/resource/issues/20

**Comment by elf-pavlik** [comment]
On process side
* https://www.wikidata.org/wiki/Q7208175
* https://www.wikidata.org/wiki/Q278061
* https://www.wikidata.org/wiki/Q13222335

**Comment by fosterlynn** [comment]
>On process side

Nice!
