### ISSUE TITLE
Start to model process for discussion

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/process#5]
I started to model Process.  This is the simplest I could make it for starting a discussion.  This is only actuals (no recipe, no plan or commitment).  It is only assembly type processes, making things out of other things.  And it is missing some properties.  But I'm sure there are lots of things to discuss even with this scope!  I expect it to be torn apart!  :smile:   

(If anyone thinks we should start with something smaller, like ValueFlow (economic event) or EconomicResource, that would be fine too.  My thinking was to put those things into something more concrete to think about.)

UML attempt
![process_uml](https://cloud.githubusercontent.com/assets/3776081/11023068/3664e9fc-8634-11e5-9b17-bc54b200af3c.png)

RDF attempt (sort of - I know I need to do some more RDF think on this!)
![processrdf](https://cloud.githubusercontent.com/assets/3776081/11023070/485b3b7a-8634-11e5-9d1d-f05e41076d1f.png)

Thinking ahead to some possible questions:
- A ValueFlow (economic event) needs to reference a EconomicResource or a ResourceType (maybe should be EconomicResourceType? or other name?).  It needs the ResourceType if the economic resource is not inventoried for whatever reason.
- Each subclass of ValueFlow would know its effect on the EconomicResource, e.g. increase, decrease, leave the same.
- isSubstitutable means any EconomicResource of the same ResourceType can be substituted for any other EconomicResource of the ResourceType.  
- We need a standard unit thingy.  I need to go back and study the one @ahdinosaur had a while back....

**Comment by fosterlynn** [comment]
Starting to revisit Process.  Here is the unit of measure vocab referenced above: http://www.linkedmodel.org/doc/qudt-vocab-quantities/1.1/index.html

**Comment by elf-pavlik** [comment]
Do you see *vf:Work* as specific *vf:Flow* or specific *vf:Resource* which goes into *vf:Consume* flow?
I see *vf:Work* as specific *vf:Resource* which can participate in *vf:Exchange* and in *vf:Process* goes into *vf:Consume* input.

**Comment by bhaugen** [comment]
Work does not get consumed. (This gets back to what we used to call event types, see https://github.com/valueflows/valueflows/issues/124 ). The flow behavior is different. Usually different (broad in a skos sense) resource types require different event behavior.

Consumed is about resources that are gone when they go into a process. We could even differentiate assembly vs incorporation (I know there's a better word for incorporate but can't find it now: the diff is that assembled inputs can be disassembled, incorporated ones can't).

Use is for equipment, tools, space, etc. that is relatively unchanged by the experience except maybe some wear and tear.

Human labor is different. I'll come back later with a longer description. Likewise currencies, likewise energy.

These differences affect coordination, they are not just academic.

**Comment by elf-pavlik** [comment]
Following [Product vs. Service](https://github.com/valueflows/resource/issues/15) thread, where Product means *MaterialGood* (or bad :wink: ). What type of input (which [verb](https://github.com/valueflows/process/blob/master/Input.md#verbs)) services go into?
From *work*, *consume*, *use*, *cite* only *work* seems to fit.

**Comment by bhaugen** [comment]
Material goods are produced in processes. Work and many other resources may be inputs to the process, where the material good (or bad) is the output).

So if you mean the inputs to a process that produces a material good, any of those verbs would fit.

If you mean the next event for the material good, it could be a transfer, or it could be consume or use.

**Comment by elf-pavlik** [comment]
> So if you mean the inputs to a process that produces a material good, any of those verbs would fit.

No, I mean "Which verb, from ones defined in [vf:Input](https://github.com/valueflows/process/blob/master/Input.md), one can use when Service goes into the Process" For example
"a movie shot" process takes as one of the inputs "applying makeup to actors" which seems similar to "inspecting teeth" service from [Dental Case](https://github.com/valueflows/valueflows/blob/master/use-cases/dental-care.md) use case.

**Comment by fosterlynn** [comment]
>No, I mean "Which verb, from ones defined in vf:Input, one can use when Service goes into the Process" For example
"a movie shot" process takes as one of the inputs "applying makeup to actors" which seems similar to "inspecting teeth" service from Dental Case use case. 

Interesting question.  I think it could be consumed.  If not, then we would need a new one for inputing services.  @bhaugen what do you think?

**Comment by bhaugen** [comment]
I'm waiting for some feedback from the REA gang.

**Comment by elf-pavlik** [comment]
Which verb we use in *vf:Transportation* on inputs for shipped *vf:MaterialItem* or passengers? Non of currently defined seem to fit. For outputed *vf:Service* 'create' seems to work just fine.

**Comment by fosterlynn** [comment]
I'm not sure passengers are an input, doesn't seem right.  All the things needed to provide the service are inputs, using existing verbs.  And yes, 'create' the service seems fine for output.

Thinking about shipping packages..... I think it should be the same, the service is the output, not the package at a different location.  Seem correct?  I don't feel 100% confident.  Perhaps it need some special treatment?

**Comment by elf-pavlik** [comment]
The process **depends** on presence of passengers and packages. One of the steps in such process - "load packages", "board passengers". I agree that transported resource or person connect to the service (created output) with some kind of *benefit* (~ consume) relationship, but at the same time process depends on their presence and can't execute without them.

**Comment by fosterlynn** [comment]
It's possible we need one or two new event types for vf:Transportation of material items, I don't know.  We had the same kind of problem for workflow processes, where the resource went into the process and the same resource came out, presumably in better shape.  Like editing a document, or repairing a bike.

**Comment by elf-pavlik** [comment]
> Like editing a document, or repairing a bike

do you get as output of that process a 'repaired bike' (vf:MaterialItem) or 'repair service' (vf:Service) ?

**Comment by bhaugen** [comment]
Both. You get the repaired bike (same bike in a different state, maybe with some new parts), and you have a reciprocity responsibility for the repair service. The inputs to the repair service probably included the bike in need of repair, some new parts, use of some tools and maybe a garage, and some repair work which required some skill.

**Comment by fosterlynn** [comment]
@bhaugen would you create a resource of the repair service as an output, with some repair service resource type? And the bike is another (secondary) output?  I can't think of anywhere we have actually run into that in a network yet.  Hmmm.

**Comment by fosterlynn** [comment]
How about a service output with underlying resource of the bike?

**Comment by elf-pavlik** [comment]
Sounds like [Equipment Repair](https://github.com/valueflows/valueflows/blob/master/use-cases/equipment-repair.md) use case. Where given resource appears in both. Should we merge that use case into [Bike Repair](https://github.com/valueflows/valueflows/blob/master/use-cases/circular-economy/broken-bike-repair.md) use case?

**TODO**
* [ ] define verb for input (the bike to repair)
* [ ] define verb for output (the repaired bike)

If we can have bike as both input and output of *repair* process which also outputs *repair service*. Why can't we have bike as both input and output of *transport* process which also outputs *transport service*. We could give input verb *pickup* and output verb *dropof*, here sub class *vf:Transport* comes handy since we can state in [proces.ttl](https://github.com/valueflows/process/blob/master/process.ttl)

```ttl
vf:pickup
  a rdf:Property ;
  rdfs:label "pick-up" ;
  rdfs:subPropertyOf vf:inflow ;
  rdfs:domain vf:Resource ;
  rdfs:range vf:Transportation .

vf:dropoff
  a rdf:Property ;
  rdfs:label "drop-off" ;
  rdfs:subPropertyOf vf:outflow ;
  rdfs:domain vf:Transportation ;
  rdfs:range vf:Resource .
```

[preview it in WebVOWL](http://vowl.visualdataweb.org/webvowl/index.html#iri=https://gist.githubusercontent.com/elf-pavlik/41b51a65d02c61cb7ac174c1d4e73e4c/raw/9e9f0ed608201b57cdd81b320eeeebb8880c95e1/vf:Process.ttl)

**Comment by fosterlynn** [comment]
The repair and the transportation use cases do seem to have similarity of structural questions.

(And yeah, probably no need for two repair use cases.)

I'm still bothered by 2 outputs, the service and the bike.  Can't quite put my finger on it yet.  They are not really different outputs like a product and an incidental waste stream.  It's more like one bundled output.

In transportation of a package, I more see the service as the output.  Although you do want to record the change of location of the package.

I haven't thought of anything I don't like about using underlying resource in the output.  Although that could happen.

**Comment by elf-pavlik** [comment]
[quick WebVOWL](http://vowl.visualdataweb.org/webvowl/index.html#iri=https://gist.githubusercontent.com/elf-pavlik/41b51a65d02c61cb7ac174c1d4e73e4c/raw/9836413081f9d423810067f8075f679506c0070f/vf:Process.ttl) which shows **events**:
* *drop-off* (out from a vf:Transportation)
* *accept* (in to the vf:Transformation / vf:Maintenance)
* *return* (out of the vf:Transformation / vf:Maintenance)
* *pick-up* (in to a vf:Transportation)

that sounds a bit like repairing a bike in some workshop would look

**Comment by bhaugen** [comment]
I think the bike repair (or anything repair) has those two outputs. You get your repaired item back, and you get a bill for the service. What's the problem?

**Comment by fosterlynn** [comment]
>I think the bike repair (or anything repair) has those two outputs. You get your repaired item back, and you get a bill for the service. What's the problem?

OK let's go with that.  

>Why can't we have bike as both input and output of transport process which also outputs transport service. 

And for transport too.

**Comment by fosterlynn** [comment]
> define verb for input (the bike to repair)
> define verb for output (the repaired bike)

> accept (in to the vf:Transformation / vf:Maintenance)
> return (out of the vf:Transformation / vf:Maintenance)

In NRP, we ended up with "To be changed" and "Changed".  We never liked it much.

Accept and Return are more clear words, but I think more narrow.  Works for repair, but not as much for steps in translation, another example with the main input and main output the same resource but improved.  In translation, the resource (the translated document) goes through several processes in sequence until it is done. https://github.com/valueflows/valueflows/blob/master/use-cases/guerrilla-translation.md

Actually, Accept might work well for about any workflow-ish thing, I like it.  Maybe some other output verb that covers returning or sending it on?

**Comment by elf-pavlik** [comment]
> Actually, Accept might work well for about any workflow-ish thing, I like it. Maybe some other output verb that covers returning or sending it on? 

Let's please keep in mind that pretty much only people developing software will stay exposed to terminology defined in vf: namespace directly. In various applications they can create UX using whatever terminology suits their context, domain or audience. For people working with software *return* might come pretty intuitive for output of a process, another geek friendly term *exit* or *ready*.
In any case where we can agree on some approach but can not agree on particular english language word. We can use very long codename for it eg. 'vf-wip:sameResourceThatOnInputButOnOutput' or even just identify it with UUID 'vf-wip:73304fd2-430d-4633-b8b2-7fa18a9ff8cb'. We could also use distinct 'work in progress' namespace for that. Anything that will allow us to experiment with those terms in data snippets we write. I would like to avoid that in some innocent way 'bikeshedding' choice of english language word, stops us from confronting our design choices with reality of use cases that should drive our work.

**Comment by fosterlynn** [comment]
>Let's please keep in mind that pretty much only people developing software will stay exposed to terminology defined in vf: namespace directly

I see some truth to that, and of course there is the English language limitation there.  But as a business analyst a lot of my career, I saw that consistent and clear language between devs and users was important, there's a lot of blurring of roles.  Ontologies especially seem like the naming is important (more than code, say).

But I promise to try not to let bikeshedding get in the way of progress, just kick me.  :)  We should of course keep going while playing with the names.

How about Accept and Improve for now?

**Comment by elf-pavlik** [comment]
> How about Accept and Improve for now?

:+1: I'll make PR with *accept* and *improve*

Can we pick up a first draft verbs specific for vf:Transport? any objections to start with *pickup* & *dropoff* and iterate from there?

**Comment by fosterlynn** [comment]
>any objections to start with pickup & dropoff and iterate from there?

No objections, can iterate from there.  Wondering if we need separate verbs, but fine for now. :+1:

**Comment by bhaugen** [comment]
I think separate verbs are useful with transport, at least for now.

**Comment by ahdinosaur** [comment]
> @elf-pavlik says: Let's please keep in mind that pretty much only people developing software will stay exposed to terminology defined in vf: namespace directly.

> @fosterlynn says: I see some truth to that, and of course there is the English language limitation there. But as a business analyst a lot of my career, I saw that consistent and clear language between devs and users was important, there's a lot of blurring of roles. Ontologies especially seem like the naming is important (more than code, say).

i really hope our vocabulary is not only for devs, that would be a huge loss.

regarding the influx of new terms, keen to iterate where we refine and distill common terms that work across our use cases, i'm wary of becoming yet another overly complicated vocabulary with a new term for every slightly different use case. that being said, y'all are great and i'm loving the progress. :)

**Comment by bhaugen** [comment]
New terms should be justified, although I'm fine with experiments. Sometimes, though, a new term can make usability easier than overloading another term. Sweet spots in that design space, as always.

I wrote [over here](https://github.com/valueflows/valueflows/issues/125#issuecomment-219600608) what I personally think we should shoot for as a range of representations, one being plain text glossary, another being interactive explorer.

**Comment by elf-pavlik** [comment]
> @elf-pavlik
do you get as output of that process a 'repaired bike' (vf:MaterialItem) or 'repair service' (vf:Service) ?

> @bhaugen 
Both. You get the repaired bike (same bike in a different state, maybe with some new parts), and you have a reciprocity responsibility for the repair service. The inputs to the repair service probably included the bike in need of repair, some new parts, use of some tools and maybe a garage, and some repair work which required some skill.

> @fosterlynn 
@bhaugen would you create a resource of the repair service as an output, with some repair service resource type? And the bike is another (secondary) output? I can't think of anywhere we have actually run into that in a network yet. Hmmm.

Transportation example seems to confirm that we need service resources as outputs, besides events representing the resource, which receives the service, entering and leaving the process.
https://github.com/valueflows/process/issues/9#issuecomment-237677830
