### ISSUE TITLE
Making/assembling processes

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/process#7]
I like this type of thing to start with, I think it is conceptually the simplest and very concrete.  I'm starting a new issue because the original model issue is more broad, as well as old. :)  

This reflects use cases: 
- [3D printed part](https://github.com/valueflows/valueflows/blob/master/use-cases/make-3d-printed-part.md)
- [Combine lots](https://github.com/valueflows/valueflows/blob/master/use-cases/combine-lots.md)
- [Pottery](https://github.com/valueflows/valueflows/blob/master/use-cases/potter-1.md) (the process part, which is basically like the 3d printed part one))

Will start commenting with suggestions using loosely documented data/vocab, then moving to more rigorous doc. :)

**Comment by fosterlynn** [comment]
3D printed part use case (link above).  Key pieces of data.

Process:
    - Name: Cool part design
    - Context: Sensorica Digital Fab Project
    - Notes: 
    - Estimated start date: 2016/3/1
    - Estimated end date: 2016/3/10
    - Finished: true
    -- Inflows:
    ---- Work flow:
    ------ Date: 2016/3/2
    ------ Agent: Daniel
    ------ Quantity: 5
    ------ Unit: Hours
    ------ Resource type (type of work): 3D design
    ------ Notes:
    ---- Work flow:
    ------ Date: 2016/3/5
    ------ Agent: Daniel
    ------ Quantity: 3.5
    ------ Unit: Hours
    ------ Resource type (type of work): 3D design
    ------ Notes: 
    -- Outflows:
    ---- Produce flow:
    ------ Date: 2016/3/5
    ------ Quantity: 1
    ------ Unit: Each
    ------ Resource type: 3D printed part design
    ------ Resource: Cool part 5 design
    ------ Notes: 

Process:
    - Name: Produce cool part
    - Context: Sensorica Digital Fab Project
    - Notes: 
    - Estimated start date: 2016/3/10
    - Estimated end date: 2016/3/10
    - Finished: true
    -- Inflows:
    ---- Work flow:
    ------ Date: 2016/3/10
    ------ Agent: Jim
    ------ Quantity: 4
    ------ Unit: Hours
    ------ Resource type (type of work): 3D printing
    ------ Notes:
    ---- Use flow:
    ------ Date: 2016/3/10
    ------ Agent: Jim
    ------ Quantity: 4
    ------ Unit: Hours
    ------ Resource type: 3D printer
    ------ Resource: ORD Solutions FDM 3D printer
    ------ Notes: 
    ---- Consume flow:
    ------ Date: 2016/3/10
    ------ Agent: Jim
    ------ Quantity: 230
    ------ Unit: Grams
    ------ Resource type: PLA-PHA BambooFill 1.75mm
    ------ Notes: 
    ---- Cite flow:
    ------ Date: 2016/3/10
    ------ Agent: Jim
    ------ Quantity: 20
    ------ Unit: Percent
    ------ Resource type: 3D printed part design
    ------ Resource: Cool part 5 design
    ------ Notes: The design worked great, although I had to make a small modification to....
    -- Outflows:
    ---- Produce flow:
    ------ Date: 2016/3/10
    ------ Quantity: 1
    ------ Unit: Each
    ------ Resource type: 3D printed part
    ------ Resource: Jim's Cool part 5
    ------ Notes: 

These hook together like so:

Process: Cool part design >> Produce flow >> Resource: Cool part 5 design >> Cite flow >> Process: Produce cool part

Generalized: Resource >> Inflow >> Process >> Outflow >> Resource >> Inflow >> Process >> Outflow >> Resource...

**Comment by elf-pavlik** [comment]
great start @fosterlynn! would you like to try writing a YAML version of above?

**Comment by fosterlynn** [comment]
@elf-pavlik feel free to vf:accept and vf:improve! :smile: 

```yml
'@context':
  qudt: http://qudt.org/1.1/schema/qudt#
  unit: http://qudt.org/1.1/schema/unit#
  vf: https://w3id.org/valueflows/
  ex: https://example.org/

'@graph':

  - '@id': ex:Cool-part-design-2016-03-01
    '@type': vf:Process
    'vf:processType': ex:3d-design
    'vf:context': urn:ex:Sensorica-Digital-Fab-Project
    'vf:estimatedStart': 2016/3/1
    'vf:estimatedEnd': 2016/3/10
    'vf:flow':
      - '@id': ex:input-1
        'vf:date': 2016/3/2
        'vf:verb': vf:work
        'vf:involvedAgent': ex:Daniel
        'vf:resource': 'vf:resourceType': ex:3D-design-work
        'vf:amount':
            '@type': qudt:QuantityValue
            'qudt:unit': unit:Hours
            'qudt:numericValue': 5
        'vf:note': Creating using my CAD tool. Expect to be done before the due date.
      - '@id': ex:input-2
        'vf:date': 2016/3/5
        'vf:verb': vf:work
        'vf:involvedAgent': ex:Daniel
        'vf:resource': 'vf:resourceType': ex:3D-design-work
        'vf:amount':
            '@type': qudt:QuantityValue
            'qudt:unit': unit:Hours
            'qudt:numericValue': 3.5
      - '@id': ex:output-1
        'vf:date': 2016/3/5
        'vf:verb': vf:produce
        'vf:involvedAgent': urn:ex:Sensorica-Digital-Fab-Project
        'vf:resource': urn:ex:cool-part-5-design
        'vf:amount':
            '@type': qudt:QuantityValue
            'qudt:unit': unit:Each
            'qudt:numericValue': 1

  - '@id': ex:cool-part-5-design
    '@type': vf:Resource
    'vf:resourceType': urn:ex:3D-design
    'vf:amount':
      '@type': qudt:QuantityValue
      'qudt:unit': unit:Each
      'qudt:numericValue': 1
    '@reverse': 'vf:flow': ex:output-1

  - '@id': ex:Produce-cool-part-2016-03-10
    '@type': vf:Process
    'vf:processType': ex:3d-printing
    'vf:context': urn:ex:Sensorica-Digital-Fab-Project
    'vf:estimatedStart': 2016/3/10
    'vf:estimatedEnd': 2016/3/10
    'vf:flow':
      - '@id': ex:input-3
        'vf:date': 2016/3/10
        'vf:verb': vf:work
        'vf:involvedAgent': ex:Jim
        'vf:resource': 'vf:resourceType': ex:3D-printing-work
        'vf:amount':
            '@type': qudt:QuantityValue
            'qudt:unit': unit:Hours
            'qudt:numericValue': 4
      - '@id': ex:input-4
        'vf:date': 2016/3/10
        'vf:verb': vf:use
        'vf:resource': urn:ex:ORD-Solutions-FDM-3d-printer-123345
        'vf:amount':
            '@type': qudt:QuantityValue
            'qudt:unit': unit:Hours
            'qudt:numericValue': 4
      - '@id': ex:input-5
        'vf:date': 2016/3/10
        'vf:verb': vf:consume
        'vf:resource': urn:ex:PLA-PHA-BambooFill-1.75mm
        'vf:amount':
            '@type': qudt:QuantityValue
            'qudt:unit': unit:Grams
            'qudt:numericValue': 230
      - '@id': ex:input-6
        'vf:date': 2016/3/10
        'vf:verb': vf:cite
        'vf:resource': urn:ex:cool-part-5-design
        'vf:amount':
            '@type': qudt:QuantityValue
            'qudt:unit': unit:Percent
            'qudt:numericValue': 20
      - '@id': ex:output-2
        'vf:date': 2016/3/10
        'vf:verb': vf:produce
        'vf:involvedAgent': urn:ex:Sensorica-Digital-Fab-Project
        'vf:resource': urn:ex:cool-part-5-lab
        'vf:amount':
            '@type': qudt:QuantityValue
            'qudt:unit': unit:Each
            'qudt:numericValue': 5

  - '@id': ex:cool-part-5-lab
    '@type': vf:Resource
    'vf:resourceType': urn:ex:cool-part-5
    'vf:amount':
      '@type': qudt:QuantityValue
      'qudt:unit': unit:Each
      'qudt:numericValue': 10
    '@reverse': 
        'vf:flow': ex:output-2
        'vf:flow': ex:output-8
```

A few notes:

* I changed your @reverse to reference a flow (rea:EconomicEvent) rather than a resource.
* The last process added to an existing resource.
* On the resources, should we be doing it more like this?
```yml
    '@type': 
       vf:Resource
       urn:ex:cool-part-5
```

**Comment by fosterlynn** [comment]
Here is some tentative YAML for a recipe for this. 

```yml
'@context':
  qudt: http://qudt.org/1.1/schema/qudt#
  unit: http://qudt.org/1.1/schema/unit#
  vf: https://w3id.org/valueflows/
  ex: https://example.org/

'@graph':

  - '@id': ex:3D-part
    '@type': vf:ResourceType
    'vf:unit': 'qudt:unit': unit:Each
    'vf:isSubstitutable': False
    'vf:inventoryRule': keepInventory
    'vf:note': This is a generic recipe for creating 3D parts.
    
  - '@id': ex:Design-3D-part
    '@type': vf:ProcessType
    'vf:estimatedDuration':
        '@type': qudt:QuantityValue
        'qudt:unit': unit:Days
        'qudt:numericValue': 5
    'vf:recipe':
      - '@id': ex:input-1-recipe
        'vf:verb': vf:work
        'vf:resourceType': ex:3D-design-work
        'vf:amount':
            '@type': qudt:QuantityValue
            'qudt:unit': unit:Hours
            'qudt:numericValue': 10
      - '@id': ex:output-1-recipe
        'vf:verb': vf:produce
        'vf:resourceType': ex:3D-design
        'vf:amount':
            '@type': qudt:QuantityValue
            'qudt:unit': unit:Each
            'qudt:numericValue': 1

  - '@id': ex:Produce-3D-part
    '@type': vf:ProcessType
    'vf:processType': ex:3d-printing
    'vf:estimatedDuration':
        '@type': qudt:QuantityValue
        'qudt:unit': unit:Days
        'qudt:numericValue': 1
    'vf:recipe':
      - '@id': ex:input-3-recipe
        'vf:verb': vf:work
        'vf:resourceType': ex:3D-printing-work
        'vf:amount':
            '@type': qudt:QuantityValue
            'qudt:unit': unit:Hours
            'qudt:numericValue': 1
      - '@id': ex:input-4-recipe
        'vf:verb': vf:use
        'vf:resourceType': ex:3D-printer
        'vf:amount':
            '@type': qudt:QuantityValue
            'qudt:unit': unit:Hours
            'qudt:numericValue': 1
      - '@id': ex:input-5-recipe
        'vf:verb': vf:consume
        'vf:resourceType': ex:3D-polymer
        'vf:amount':
            '@type': qudt:QuantityValue
            'qudt:unit': unit:Grams
            'qudt:numericValue': 100
      - '@id': ex:input-6-recipe
        'vf:verb': vf:cite
        'vf:resourceType': ex:3D-design
      - '@id': ex:output-2-recipe
        'vf:verb': vf:produce
        'vf:resourceType': ex:3D-part
        'vf:amount':
            '@type': qudt:QuantityValue
            'qudt:unit': unit:Each
            'qudt:numericValue': 1
```

Here is some tentative YAML for commitments that could have occurred prior to the production work

```yml
'@context':
  qudt: http://qudt.org/1.1/schema/qudt#
  unit: http://qudt.org/1.1/schema/unit#
  vf: https://w3id.org/valueflows/
  ex: https://example.org/

'@graph':

  - '@id': ex:Cool-part-design-2016-03-01
    '@type': vf:Process
    'vf:processType': ex:3d-design
    'vf:context': urn:ex:Sensorica-Digital-Fab-Project
    'vf:estimatedStart': 2016/3/1
    'vf:estimatedEnd': 2016/3/10
    'vf:plan':
      - '@id': ex:input-1-plan
        'vf:dueDate': 2016/3/10
        'vf:verb': vf:work
        'vf:resourceType': ex:3D-design-work
        'vf:amount':
            '@type': qudt:QuantityValue
            'qudt:unit': unit:Hours
            'qudt:numericValue': 10
        'vf:note': If this will take longer than 10 hours, please notify Jim.
      - '@id': ex:output-1-plan
        'vf:dueDate': 2016/3/10
        'vf:verb': vf:produce
        'vf:resourceType': ex:3D-design
        'vf:amount':
            '@type': qudt:QuantityValue
            'qudt:unit': unit:Each
            'qudt:numericValue': 1
        'vf:note': This design should be usable by FDM and other printers.

  - '@id': ex:Produce-cool-part-2016-03-10
    '@type': vf:Process
    'vf:processType': ex:3d-printing
    'vf:context': urn:ex:Sensorica-Digital-Fab-Project
    'vf:estimatedStart': 2016/3/10
    'vf:estimatedEnd': 2016/3/10
    'vf:plan':
      - '@id': ex:input-3-plan
        'vf:dueDate': 2016/3/10
        'vf:verb': vf:work
        'vf:resourceType': ex:3D-printing-work
        'vf:amount':
            '@type': qudt:QuantityValue
            'qudt:unit': unit:Hours
            'qudt:numericValue': 5
      - '@id': ex:input-4-plan
        'vf:dueDate': 2016/3/10
        'vf:verb': vf:use
        'vf:resourceType': ex:ORD-Solutions-FDM-3d-printer
        'vf:amount':
            '@type': qudt:QuantityValue
            'qudt:unit': unit:Hours
            'qudt:numericValue': 5
      - '@id': ex:input-5-plan
        'vf:date': 2016/3/10
        'vf:verb': vf:consume
        'vf:resourceType': ex:PLA-PHA-BambooFill-1.75mm
        'vf:amount':
            '@type': qudt:QuantityValue
            'qudt:unit': unit:Grams
            'qudt:numericValue': 220
      - '@id': ex:input-6-plan
        'vf:date': 2016/3/10
        'vf:verb': vf:cite
        'vf:resourceType': ex:3D-design
        'vf:amount':
            '@type': qudt:QuantityValue
            'qudt:unit': unit:Percent
            'qudt:numericValue': 10
      - '@id': ex:output-2-plan
        'vf:date': 2016/3/10
        'vf:verb': vf:produce
        'vf:involvedAgent': urn:ex:Sensorica-Digital-Fab-Project
        'vf:resourceType': ex:3D-part
        'vf:amount':
            '@type': qudt:QuantityValue
            'qudt:unit': unit:Each
            'qudt:numericValue': 5
```

**Comment by elf-pavlik** [comment]
we can't nest YAML like that, we need new lines
```yaml
'vf:flow':
      - '@id': ex:input-1
        'vf:date': 2016/3/2
        'vf:verb': vf:work
        'vf:involvedAgent': ex:Daniel
        'vf:resource': 'vf:resourceType': ex:3D-design-work
        'vf:amount':
            '@type': qudt:QuantityValue
            'qudt:unit': unit:Hours
            'qudt:numericValue': 5
        'vf:note': Creating using my CAD tool. Expect to be done before the due date.
```
so we can describe resource like that
```yaml
'vf:flow':
      - '@id': ex:input-1
        'vf:date': 2016/3/2
        'vf:verb': vf:work
        'vf:involvedAgent': ex:Daniel
        'vf:resource':
          '@type': vf:Resource
          'vf:resourceType': ex:3D-design-work
        'vf:amount':
            '@type': qudt:QuantityValue
            'qudt:unit': unit:Hours
            'qudt:numericValue': 5
        'vf:note': Creating using my CAD tool. Expect to be done before the due date.
```

`ex:3D-design-work` looks to me like a vf:Service but I will follow up on that in another issue (not to drift here)

This use of reverse doesn't seem to make sense

```yaml
  - '@id': ex:cool-part-5-design
    '@type': vf:Resource
    'vf:resourceType': urn:ex:3D-design
    'vf:amount':
      '@type': qudt:QuantityValue
      'qudt:unit': unit:Each
      'qudt:numericValue': 1
    '@reverse': 'vf:flow': ex:output-1
```

Currently we have defined classes for n-ary relations [vf:Input](https://github.com/valueflows/process/blob/master/Input.md) and [vf:Output](https://github.com/valueflows/process/blob/master/Input.md). So you could write:

```yaml
  - '@id': ex:cool-part-5-design
    '@type': vf:Resource
    'vf:resourceType': urn:ex:3D-design
    '@reverse':
      'vf:resource':
        '@id': ex:output-1
        '@type': vf:Output
```

Since verbs mark direction, we may replace *vf:Output* and *vf:Input* with one class for such n-ary relation *vf:Flow*, *vf:Event* (but that implies 'Observation'), *vf:Port* (also topic for another issue in this repo)

Above use of `@reverse` pretty much duplicates this data

```yaml
     - '@id': ex:output-1
        'vf:resource': urn:ex:cool-part-5-design
```

If you don't find it clear I can explain in on chat with examples above in Turtle syntax. Maybe even N3 would make it even clearer with its syntax for using properties in reverse direction
```n3
ex:cool-part-5-design is vf:resource of ex:output-1
```

in turtle you need to write always following the direction of predicate (property)

```ttl
ex:output-1 vf:resource ex:cool-part-5-design
```

I see that you use `ex:PLA-PHA-BambooFill-1.75mm` in inconsistent way, sometimes you use it to identify the type
```yaml
      - '@id': ex:input-5-plan
        'vf:date': 2016/3/10
        'vf:verb': vf:consume
        'vf:resourceType': ex:PLA-PHA-BambooFill-1.75mm
```

and sometimes to identify **instance** of that type the 'stock resoruce'

```yaml
      - '@id': ex:input-5
        'vf:date': 2016/3/10
        'vf:verb': vf:consume
        'vf:resource': urn:ex:PLA-PHA-BambooFill-1.75mm
```

How do you define meaning of `vf:inventoryRule: keepInventory` in 
```yaml
  - '@id': ex:3D-part
    '@type': vf:ResourceType
    'vf:unit': 'qudt:unit': unit:Each
    'vf:isSubstitutable': False
    'vf:inventoryRule': keepInventory
    'vf:note': This is a generic resource type for 3D parts.
```

**Comment by elf-pavlik** [comment]
Having such 'plan'
```yaml
  'vf:plan':
      - '@id': ex:input-5-plan
        'vf:date': 2016/3/10
        'vf:verb': vf:consume
        'vf:resourceType': ex:PLA-PHA-BambooFill-1.75mm
        'vf:amount':
            '@type': qudt:QuantityValue
            'qudt:unit': unit:Grams
            'qudt:numericValue': 220
```

You only reference a type of the needed resource. When do you allocate the actual resource for this process? In a way we can consider it binding *an instance* of `ex:ORD-Solutions-FDM-3d-printer` to that input. We only can *vf:consume* instances of *vf:Resource*, not instances of *vf:ResourceType*, so above still looks like a recipe not a plan which one can really execute...

**Comment by fosterlynn** [comment]
>You only reference a type of the needed resource. When do you allocate the actual resource for this process?

In this example, I'm assuming the resource gets allocated on the Observation layer, not in the plan.  There might be several processes that will want that same resource, there might have been some ordered that will be here soon, etc.  This is a substitutable resource.  Might be different in other situations, where you need to reserve a specific resource.

**Comment by fosterlynn** [comment]
>I see that you use ex:PLA-PHA-BambooFill-1.75mm in inconsistent way

Oops.  I fixed it in the Observation layer yaml, added "-lab".

**Comment by bhaugen** [comment]
To see how resource usage gets allocated, look for https://www.google.com/?ion=1&espv=2#q=room+scheduling+software
It's the same problem.

**Comment by fosterlynn** [comment]
>we can't nest YAML like that, we need new lines

Thanks!  Fixed in previous comment.

**Comment by fosterlynn** [comment]
>This use of reverse doesn't seem to make sense

OK, probably some misunderstanding of @reverse on my part.

But I am trying to say: The owl:Class of the thing identified by ```'@id': ex:output-1``` is not vf:Resource, it is vf:Flow (or whatever we call rea:EconomicEvent). 

That is actually one of the key issues I'm trying to get to the bottom of in these discussions - what is a vfResource.

**Comment by elf-pavlik** [comment]
```yaml
  - '@id': ex:cool-part-5-design
    '@type': vf:Resource
    'vf:resourceType': urn:ex:3D-design
    '@reverse':
      'vf:resource':
        '@id': ex:output-1
        '@type': rea:EconomicEvent
```
